<!DOCTYPE html>
<!--[if IE 9 ]><html class="ie9"><![endif]-->
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>LIPA RENT</title>
	<link href="<?= @$this->url->get('vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css'); ?>" rel="stylesheet">
	<link href="<?= @$this->url->get('vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css'); ?>" rel="stylesheet">        
	<link href="<?= @$this->url->get('vendors/bower_components/google-material-color/dist/palette.css'); ?>" rel="stylesheet">

	<?php $this->assets->outputCss('css'); ?>

	<link href="<?= @$this->url->get('css/app.min.1.css'); ?>" rel="stylesheet">
	<link href="<?= @$this->url->get('css/app.min.2.css'); ?>" rel="stylesheet">
</head>
<body data-ma-header="teal">
	<header id="header" class="media">
		<div class="pull-left h-logo">
			<a href="index.html" class="hidden-xs">
				LIPARENT
				<small>Tenant Portal</small>
			</a>

			<div class="menu-collapse" data-ma-action="sidebar-open" data-ma-target="main-menu">
				<div class="mc-wrap">
					<div class="mcw-line top palette-White bg"></div>
					<div class="mcw-line center palette-White bg"></div>
					<div class="mcw-line bottom palette-White bg"></div>
				</div>
			</div>
		</div>
		<ul class="pull-right h-menu">
		<li class="hm-search-trigger">
		<a href="#" data-ma-action="search-open">
		<i class="hm-icon zmdi zmdi-search"></i>
		</a>
		</li>

		<li class="dropdown hidden-xs hidden-sm h-apps">
		<a data-toggle="dropdown" href="#">
		<i class="hm-icon zmdi zmdi-apps"></i>
		</a>
		<ul class="dropdown-menu pull-right">
		<li>
		<a href="#">
		<i class="palette-Red-400 bg zmdi zmdi-calendar"></i>
		<small>Calendar</small>
		</a>
		</li>

		<li>
		<a href="#">
		<i class="palette-Green-400 bg zmdi zmdi-file-text"></i>
		<small>Files</small>
		</a>
		</li>
		<li>
		<a href="#">
		<i class="palette-Light-Blue bg zmdi zmdi-email"></i>
		<small>Mail</small>
		</a>
		</li>
		<li>
		<a href="#">
		<i class="palette-Orange-400 bg zmdi zmdi-trending-up"></i>
		<small>Analytics</small>
		</a>
		</li>
		<li>
		<a href="#">
		<i class="palette-Purple-300 bg zmdi zmdi-view-headline"></i>
		<small>News</small>
		</a>
		</li>
		<li>
		<a href="#">
		<i class="palette-Blue-Grey bg zmdi zmdi-image"></i>
		<small>Gallery</small>
		</a>
		</li>
		</ul>
		</li>
		<li class="dropdown hidden-xs">
		<a data-toggle="dropdown" href="#"><i class="hm-icon zmdi zmdi-more-vert"></i></a>
		<ul class="dropdown-menu dm-icon pull-right">
		<li class="hidden-xs">
		<a data-action="fullscreen" href="#"><i class="zmdi zmdi-fullscreen"></i> Toggle Fullscreen</a>
		</li>
		<li>
		<a data-action="clear-localstorage" href="#"><i class="zmdi zmdi-delete"></i> Clear Local Storage</a>
		</li>
		<li>
		<a href="#"><i class="zmdi zmdi-face"></i> Privacy Settings</a>
		</li>
		<li>
		<a href="#"><i class="zmdi zmdi-settings"></i> Other Settings</a>
		</li>
		</ul>
		</li>
		<li class="hm-alerts" data-user-alert="sua-messages" data-ma-action="sidebar-open" data-ma-target="user-alerts">
		<a href="#"><i class="hm-icon zmdi zmdi-notifications"></i></a>
		</li>
		<li class="dropdown hm-profile">
		<a data-toggle="dropdown" href="#">
		<img src="<?= @$this->url->get('img/profile-pics/1.jpg'); ?>" alt="">
		</a>

		<ul class="dropdown-menu pull-right dm-icon">
		<li>
		<a href="profile-about.html"><i class="zmdi zmdi-account"></i> View Profile</a>
		</li>
		<li>
		<a href="#"><i class="zmdi zmdi-input-antenna"></i> Privacy Settings</a>
		</li>
		<li>
		<a href="#"><i class="zmdi zmdi-settings"></i> Settings</a>
		</li>
		<li>
		<a href="<?= @$this->url->get("auth/user/signout"); ?>"><i class="zmdi zmdi-time-restore"></i> Logout</a>
		</li>
		</ul>
		</li>
		</ul>
	</header>
	<section id="main">
		<aside id="s-main-menu" class="sidebar">
			<div class="smm-header">
				<i class="zmdi zmdi-long-arrow-left" data-ma-action="sidebar-close"></i>
			</div>
			<ul class="smm-alerts">
				<li data-user-alert="sua-messages" data-ma-action="sidebar-open" data-ma-target="user-alerts">
					<i class="zmdi zmdi-email"></i>
				</li>
				<li data-user-alert="sua-notifications" data-ma-action="sidebar-open" data-ma-target="user-alerts">
					<i class="zmdi zmdi-notifications"></i>
				</li>
				<li data-user-alert="sua-tasks" data-ma-action="sidebar-open" data-ma-target="user-alerts">
					<i class="zmdi zmdi-view-list-alt"></i>
				</li>
			</ul>

			<ul class="main-menu">
				<li>
					<a href="<?= @$this->url->get('tenant'); ?>"><i class="zmdi zmdi-view-dashboard
"></i> Dashboard</a>
				</li>
				<!-- <li>
					<a href="<?= @$this->url->get('tenant/house'); ?>"><i class="zmdi zmdi-city-alt"></i> My House</a>
				</li> -->
				<li>
					<a href="<?= @$this->url->get('tenant/payment'); ?>"><i class="zmdi zmdi-card-membership"></i> Payments</a>
				</li>
				<li>
					<a href="<?= @$this->url->get('tenant/issues'); ?>"><i class="zmdi zmdi-alert-circle"></i> Report Issues</a>
				</li>
				
				<li>
					<a href="<?= @$this->url->get("auth/user/signout"); ?>"><i class="zmdi zmdi-time-restore"></i> Logout</a>
				</li>
			</ul>
		</aside>

		<section id="content">
			<div class="container">
				<?php $this->getContent() ?>
				<?= @$content ?>
			</div>
		</section>
	</section>

	<script src="<?= @$this->url->get('vendors/bower_components/jquery/dist/jquery.min.js'); ?>"></script>
	<script src="<?= @$this->url->get('vendors/bower_components/bootstrap/dist/js/bootstrap.min.js'); ?>"></script>
	<script src="<?= @$this->url->get('vendors/bootstrap-growl/bootstrap-growl.min.js'); ?>"></script>
	<script src="<?= @$this->url->get('vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js'); ?>"></script>
        
		<!-- Placeholder for IE9 -->
		<!--[if IE 9 ]>
		    <script src="vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js'); ?>"></script>
		<![endif]-->
		<?php $this->assets->outputJs('js'); ?>

		<?php
			foreach($javascript as $script)
			{
				echo $script ;
			}
		?>
</body>
</html>