<script type="text/javascript">
$( document ).ready(function() {
    var houses_table = $('table#houses_table').dataTable();

    $.ajax({
      url: '<?=  $this->url->get("superadmin/house/gethouses") ?>',
      dataType: 'json',
      success: function(data)
      {
         //console.log(data);

        
        houses_table.fnClearTable();
        for(var i = 0; i < data.length; i++) { 
          houses_table.fnAddData([ 
            data[i][0], 
            data[i][1], 
            data[i][2], 
            data[i][3],
            data[i][4],
            data[i][5],
            data[i][6],
            data[i][7]

          ]); 
        } // End For
        // data;

         }

    });
  });

$('#save').click(function(){
  var url = "<?= @$this->url->get('superadmin/tenant/add/json'); ?>";
      $.ajax({
           type: "POST",
           url: url,
           data: $('.modal form').serialize(),
           success: function(data)
           {
              $('#assign_tenants_select').selectpicker("destroy");

              obj = jQuery.parseJSON(data);
              var tenant_id = obj.tenant_id;
              $.get("<?= @$this->url->get('superadmin/house/returntenants/json/"+tenant_id+"'); ?>", function(tenants){
                $('#assign_tenants_select').html(tenants);
                $('#assign_tenants_select').selectpicker();
              });
           }
         })
          .done(function(data){
            obj = jQuery.parseJSON(data);
              if(obj.type == "success")
              {
                  // console.log(obj);
                  swal({
                      title: "Success!", 
                      text: "Tenant was added successfully",
                      type: "success"
                  });
              }
          });
  });

function addTenant(that)
{
  data_href = $(that).attr('data-href');
  console.log(data_href);
  //console.log(that);
  $('.modal').modal();

  
  $('.modal .modal-body').load(data_href, function(data){

    obj = jQuery.parseJSON(data);
    console.log(obj);
    $('.modal h4.modal-title').text(obj.title);
    $('.modal .modal-body').html(obj.page);
    $('#add-tenant-form').find('#tenant-submit').remove();
    });
}

$('#tenant-new').click(function(event){
  event.preventDefault();
  // $('#tenant-submit').remove();
  addTenant();
});
</script>