<script type="text/javascript">
$(document).ready(function(){

	$("#flatsfields").hide();
	$("#second-view").hide();

	var latlng = new google.maps.LatLng(-1.292066, 36.821946);
	var map = new google.maps.Map(document.getElementById('map'), {
	    center: latlng,
	    zoom: 15,
	    mapTypeId: google.maps.MapTypeId.ROADMAP
	});
	var marker = new google.maps.Marker({
	    position: latlng,
	    map: map,
	    title: 'Set lat/lon values for this property',
	    draggable: true
	});
	google.maps.event.addListener(marker, 'dragend', function(event) {

	    var lat = this.getPosition().lat();
	    $('#lat').val(lat);
	    console.log(lat);

        var lng = this.getPosition().lng();
        $('#long').val(lng);
        console.log(lng);
	    // bingo!
	    // a.latLng contains the co-ordinates where the marker was dropped
	});

	$("#next").click(function(){
		// console.log("clicked");
		$("#first-view").hide();
		$("#second-view").show();
		$("#next").hide();
		$("#previous").show();
	});

	$("#previous").click(function(){
		// console.log("clicked");
		$("#second-view").hide();
		$("#first-view").show();
		$("#previous").hide();
		$("#next").show();
	});

	$('.selectpicker').selectpicker({
	});

	function commaSeparateNumber(val){
    while (/(\d+)(\d{3})/.test(val.toString())){
      val = val.toString().replace(/(\d+)(\d{3})/, '$1'+','+'$2');
    }
    return val;
  }

	$('#rentamount').keyup(function(event) {
	  // format number
	  
	  newval = $('#rentamount').val().replace(/,/g, '');

	  val = 0;

	  if (typeof(newval) != "NaN") { val = commaSeparateNumber(newval);};
	 
	 

	  if (val != "NaN")
	  {$('#rentamount').val(val);}
	  else
	  	{$('#rentamount').val('0');}
	  
	});

	function notify(from, align, icon, type, animIn, animOut, msg){
    $.growl({
        icon: icon,
        title: 'Saved. ',
        message: msg,
        url: ''
    },{
        element: 'body',
        type: type,
        allow_dismiss: true,
        placement: {
                from: from,
                align: align
        },
        offset: {
            x: 20,
            y: 85
        },
        spacing: 10,
        z_index: 1031,
        delay: 2500,
        timer: 1000,
        url_target: '_blank',
        mouse_over: false,
        animate: {
                enter: animIn,
                exit: animOut
        },
        icon_type: 'class',
        template: '<div data-growl="container" class="alert" role="alert">' +
                        '<button type="button" class="close" data-growl="dismiss">' +
                            '<span aria-hidden="true">&times;</span>' +
                            '<span class="sr-only">Close</span>' +
                        '</button>' +
                        '<span data-growl="icon"></span>' +
                        '<span data-growl="title"></span>' +
                        '<span data-growl="message"></span>' +
                        '<a href="#" data-growl="url"></a>' +
                    '</div>'
    	});
	};

	var houseadded_json = '<?= $houseadded_json;?>';
    console.log(houseadded_json);

    

    if(houseadded_json !="")
    {
    	obj = jQuery.parseJSON(houseadded_json);
    	console.log(obj.type);
     	notify(obj.type, "", "", "", "", "", obj.message);
    }
}); //end document ready

$("input[type=radio][name='housetype']").change(function(){
	if (this.value == "0")
	{
		$('#flatsfields').show();
	}
	else if (this.value == "1")
	{
		$('#flatsfields').hide();
	}

});

$('#submit').click(function(event){
	event.preventDefault();
	// alert("clicked");

	// console.log(('#house-form').val);

	// if (('#house-form').val.length === 0 )
	// {
	//     alert("uh-oh, you forgot to fill something out");
	// } 
	// else 
	// {
	//     alert("filled");
	// }
})

</script>