<div class="block-header">
	<h2>New Record</h2>
</div>
<div class="card">
    <div class="card-header">
        <h2>Add Landlord</h2>
    </div>
    <div class="card-body card-padding">
        <form role="form" method="post" action="<?= @$this->url->get('superadmin/landlord/add'); ?>">
            <div class="form-group fg-line">
                <label for="id_no">ID Number</label>
                <input type="text" class="form-control input-sm" id="id_no" name="idno"
                       placeholder="ID Number">
            </div>
            <div class="form-group fg-line">
                <label for="firstname">First Name</label>
                <input type="text" class="form-control input-sm" id="firstname" name="firstname"
                       placeholder="First Name">
            </div>
            <div class="form-group fg-line">
                <label for="firstname">Surname</label>
                <input type="text" class="form-control input-sm" id="surname" name="surname"
                       placeholder="Surname">
            </div>
            <div class="form-group fg-line">
                <label for="phone">Phone number</label>
                <input type="text" class="form-control input-sm" id="phone" name="phone"
                       placeholder="Phone">
            </div>
            <div class="form-group fg-line">
                <label for="email">Email Address</label>
                <input type="text" class="form-control input-sm" id="email" name="email"
                       placeholder="Email">
            </div>
            <button type="submit" class="btn btn-primary btn-sm m-t-10">Submit</button>
        </form>
    </div>
</div>