<div class="block-header">
    <h2>STATISTICS</h2>
</div>
<div class="mini-charts">
    <div class="row">
        <div class="col-sm-4">
            <div class="mini-charts-item bgm-cyan">
                <div class="clearfix">
                    <div class="chart chart-pie stats-pie"></div>
                    <div class="count">
                        <small>Total Tenants</small>
                        <h2>987,459</h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="mini-charts-item bgm-cyan">
                <div class="clearfix">
                    <div class="chart chart-pie stats-pie"></div>
                    <div class="count">
                        <small>Occupied houses</small>
                        <h2>356,785K</h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="mini-charts-item bgm-cyan">
                <div class="clearfix">
                    <div class="chart chart-pie stats-pie"></div>
                    <div class="count">
                        <small>Total complaints</small>
                        <h2>458,778</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-6">
</div>
<div class="col-sm-6">
    <!-- Calendar -->
    <div class="card" id="calendar-widget">
        <div class="card-header ch-alt bgm-teal">
            <div class="cwh-year"></div>
            <div class="cwh-day"></div>

            <button class="bgm-lightgreen btn btn-default bg btn-float"><i class="zmdi zmdi-plus"></i></button>
        </div>

        <div class="card-body card-padding-sm">
            <div id="cw-body"></div>
        </div>
    </div>
</div>    