<!-- <p><?php $this->flashSession->output() ?></p> -->
<div class="card">
  <div class="card-header">
      <h4>All Houses</h4>
  </div>
  <div class="card-body card-padding">
    <form>
      <div style="float: right">
          <button class="btn btn-primary btn-icon"><i class="zmdi zmdi-delete"></i></button>
      </div>
    </br></br></br>
      <table id="houses_table" class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Type</th>
            <th>Region</th>
            <th>Estate</th>
            <th>House Number</th>
            <th>Rent Amount</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </form> 
  </div>
</div>