<div class="container container-alt">
    <div class="block-header">
        <h2><?= @$username ?>
            <small><?= @$role ?>, Lipa Rent Portal</small>
        </h2>
    </div>
    <div class="card" id="profile-main">
        <div class="pm-overview c-overflow">
            <div class="pmo-pic">
                <div class="p-relative">
                </div>
                <div class="pmo-stat">
                    <h2 class="m-0 c-white">1562</h2>
                    Total Connections
                </div>
            </div>
            <div class="pmo-block pmo-contact hidden-xs">
                <h2>Contact</h2>

                <ul>
                    <li><i class="zmdi zmdi-phone"></i> <?= @$user_contacts[0] ?> </li>
                    <li><i class="zmdi zmdi-email"></i> <?= @$user_contacts[1] ?> </li>
                </ul>
            </div>
        </div>
        <div class="pm-body clearfix">
            <div role="tabpanel">
                <ul class="tab-nav tn-justified" role="tablist">
                    <li class="active"><a href="#about" aria-controls="about" role="tab" data-toggle="tab">About</a></li>
                    <li><a href="#security" aria-controls="security" role="tab" data-toggle="tab">Security</a></li>
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="about">
                        <div class="pmb-block">
                            <div class="pmbb-header">
                                <h2><i class="zmdi zmdi-account m-r-10"></i> Basic Information</h2>
                            </div>
                            <div class="pmbb-body p-l-30">
                                <div class="pmbb-view">
                                    <dl class="dl-horizontal">
                                        <dt>Full Name</dt>
                                        <dd><?= @$username ?></dd>
                                    </dl>
                                    <dl class="dl-horizontal">
                                        <dt>Current Role</dt>
                                        <dd><?= @$role ?></dd>
                                    </dl>
                                    <dl class="dl-horizontal">
                                        <dt>Date Registered</dt>
                                        <dd><?= @$date ?></dd>
                                    </dl>
                                </div>
                            </div>
                        </div>
                        <div class="pmb-block">
                            <div class="pmbb-header">
                                <h2><i class="zmdi zmdi-phone m-r-10"></i> Contact Information</h2>

                                <ul class="actions">
                                    <li class="dropdown">
                                        <a href="#" data-toggle="dropdown">
                                            <i class="zmdi zmdi-more-vert"></i>
                                        </a>

                                        <ul class="dropdown-menu dropdown-menu-right">
                                            <li>
                                                <a data-ma-action="profile-edit" >Edit</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                            <div class="pmbb-body p-l-30">
                                <div class="pmbb-view">
                                    <dl class="dl-horizontal">
                                        <dt>Mobile Phone</dt>
                                        <dd><?= @$user_contacts[0] ?></dd>
                                    </dl>
                                    <dl class="dl-horizontal">
                                        <dt>Email Address</dt>
                                        <dd><?= @$user_contacts[1] ?></dd>
                                    </dl>
                                </div>
                                <div class="pmbb-edit">
                                    <form>
                                    <dl class="dl-horizontal">
                                        <dt class="p-t-10">Mobile Phone</dt>
                                        <dd>
                                            <div class="fg-line">
                                                <input type="text" class="form-control"
                                                       placeholder="Enter new phone">
                                            </div>
                                        </dd>
                                    </dl>
                                    <dl class="dl-horizontal">
                                        <dt class="p-t-10">Email Address</dt>
                                        <dd>
                                            <div class="fg-line">
                                                <input type="email" class="form-control"
                                                       placeholder="Enter new email">
                                            </div>
                                        </dd>
                                    </dl>
                                    <div class="m-t-30">
                                        <button class="btn btn-primary btn-sm">Save</button>
                                        <button data-ma-action="profile-edit-cancel" class="btn btn-link btn-sm">Cancel</button>
                                    </div>
                                    </form>
                                </div>
                            </div>    
                        </div> <!--here-->
                                        
                    </div>
                    <div role="tabpanel" class="tab-pane" id="security">
                        <div class="pmb-block">
                            <div class="pmbb-header">
                                <h2><i class="zmdi zmdi-account-circle m-r-10"></i> Change password</h2>

                                <ul class="actions">
                                    <li class="dropdown">
                                        <a href="#" data-toggle="dropdown">
                                            <i class="zmdi zmdi-more-vert"></i>
                                        </a>

                                        <ul class="dropdown-menu dropdown-menu-right">
                                            <li>
                                                <a data-ma-action="profile-edit" >Edit</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                            <div class="pmbb-body p-l-30">
                                <div class="pmbb-view">
                                    <p>
                                        Click on the three dots to view the form
                                    </p>
                                </div>
                                <div class="pmbb-edit">
                                    <form action="<?= $this->url->get("superadmin/account/updateprofile/{$userid}/password")?>" method="post">
                                    <dl class="dl-horizontal">
                                        <dt class="p-t-10">Current email</dt>
                                        <dd>
                                            <div class="fg-line">
                                                <input type="text" class="form-control" name="curremail" value="<?= @$user_contacts[1] ?>" readonly>
                                            </div>
                                        </dd>
                                    </dl>
                                    <dl class="dl-horizontal">
                                        <dt class="p-t-10">Current password</dt>
                                        <dd>
                                            <div class="fg-line">
                                                <input type="password" class="form-control" name="currpass" placeholder="Enter current password">
                                            </div>
                                        </dd>
                                    </dl>
                                    <dl class="dl-horizontal">
                                        <dt class="p-t-10">New password</dt>
                                        <dd>
                                            <div class="fg-line">
                                                <input type="password" class="form-control" name="newpass" placeholder="Enter new password">
                                            </div>
                                        </dd>
                                    </dl>
                                    <div class="m-t-30">
                                        <button class="btn btn-primary btn-sm" id="editpass">Save</button>
                                        <button data-ma-action="profile-edit-cancel" class="btn btn-link btn-sm">Cancel</button>
                                    </div>
                                    </form>
                                </div>
                        </div>    
                    </div> <!--here-->
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>