<div class = "card">
	<div class="card-header">
		<h2><i class="zmdi zmdi-card-giftcard"></i> My Transactions<small>View your transactions here</small></h2>
	</div>

	<div class="card-body card-padding">
		<table class="table table-bordered">
			<thead>
				<th>#</th>
				<th>Payment For</th>
				<th>Transaction ID</th>
				<th>Amount</th>
				<th>Verfication</th>
				<th>Date</th>
				<th>Actions</th>
			</thead>
			<tbody>
				<?= @$payments_table; ?>
			</tbody>
		</table>
	</div>
</div>