<div class="card">
	<div class="card-header">
		<h2 class="card-title">
			<i class="zmdi zmdi-alert-circle"></i>
			Report an Issue
		</h2>
		<small>Report an issue to the administrator</small>
	</div>
	<div class="card-body card-padding" role = "form">
	<p><?php $this->flashSession->output() ?></p>
		<form method="POST" action="<?= @$this->url->get('tenant/issues/addReport'); ?>" class = "form-horizontal">
			<div class="form-group">
				<label for="issueTitle" class="col-sm-2 control-label">Issue Title</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" name = 'issueTitle' />
				</div>
			</div>

			<div class="form-group">
				<label for="issueDescription" class="col-sm-2 control-label">Issue Description</label>
				<div class="col-sm-10">
					<textarea type="text" class="form-control" name = 'issueDescription' rows = "8"></textarea>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-2"></div>
			    <div class="col-sm-10">
				    <button class = 'btn btn-primary'>Submit Issue</button>
			    </div>
			</div>
			
		</form>
	</div>
</div>