<p class="login-box-msg">Please sign in below</p>
<form action="<?= @$this->url->get('auth/user/signin'); ?>" method="post">
    <div class="input-group m-b-20">
        <span class="input-group-addon"><i class="zmdi zmdi-account"></i></span>
	        <div class="fg-line">
	            <input type="text" class="form-control" placeholder="Username" name="username">
	        </div>
    </div>

    <div class="input-group m-b-20">
        <span class="input-group-addon"><i class="zmdi zmdi-lock-outline"></i></span>
        <div class="fg-line">
            <input type="password" class="form-control" placeholder="Password" name="password">
        </div>
    </div>
    <input type = "hidden" name = '<?php echo $this->security->getTokenKey(); ?>' value = '<?php echo $this->security->getToken(); ?>' />

    <button type="submit" class="btn btn-login btn-success btn-float"><i class="zmdi zmdi-arrow-forward"></i></button>
</form>